### ISSUE TITLE
Search: inconsistent pagination

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#244]
The search returns pages for which no results are available. This issue is always reproducible.

How to reproduce:
1. After clean OpenCms installation with  default modules, search for "example" in index "Offline project EN (VFS)".
Screenshot:
![opencms_workplace_of_ admin _-_2014-05-05_15 14 16](https://cloud.githubusercontent.com/assets/790448/2878060/b0aafa2a-d457-11e3-8c16-b6c529bc2aa7.png)
2. Click on the 5th page... No matches found!
Screenshot:
![opencms_workplace_of_ admin _-_2014-05-05_15 17 29](https://cloud.githubusercontent.com/assets/790448/2878080/faa93894-d457-11e3-83f8-232adc114679.png)

**Comment by aKandzior** [comment]
Much has changed in the search since 2014, e.g. we switched from Lucene to Solr. 

Can you please check if this issues are still persisting in 9.5.2 or later?

If so, do you think it's still important to fix these Lucene search issues? Have left behind Lucene and only suggest Solr for searching since 9.5.0.

**Comment by gallardo** [comment]
I never considered this an important issue. Moreover, if memory serves, this is caused by a Lucene bug already reported somewhere else.

My guess is that anything still using Lucene displays this wrong behaviour. (The issue still persist in www.opencms.org/en/search.html.)

On the other hand, I agree that this is almost irrelevant with the migration to Solr, and thus I'm closing it.
