### ISSUE TITLE
Can not search with keywords I added in context menu SEO options 

### ISSUE THREAD

**Issue by Hatem28** [alkacon/opencms-core#309]
I added few keywords to my page by typing keywords in context menu SEO options keywords field and I publish the page, When I tried to search by using the keywords I just entered search returns no result ?

**Comment by dSeidel** [comment]
The keywords are just written to the property "Keywords". These are indexed in "Keywords_prop" - but this is not used in the default search function integrated in OpenCms. Since the keywords are more important for a search like Google, this may be ok. But you could also change it by setting up your own Solr search or adjusting /system/modules/com.alkacon.bootstrap.formatters/search/configuration.js.

Here's an adjustment:

        "autocomplete" : {
            "id" : "searchWidgetAutoComplete",
            "label" : '<fmt:message key="label.search" />',
            "fields" : [ "spell", "content_en", "content_de", "Title_exact", "Keywords_prop" ]
        },
        "autocompleteHeader" : {
            "id" : "searchWidgetAutoCompleteHeader",
            "label" : '<fmt:message key="label.search" />',
            "fields" : [ "spell", "content_en", "content_de", "Title_exact", "Keywords_prop" ]
        },

("Keywords_prop" is added for "fields").

**Comment by agkhan** [comment]
How to fix it in OpenCMS version 10 for non default site?
