### ISSUE TITLE
Downloadgallery doesn't show images after upload

### ISSUE THREAD

**Issue by jplette** [alkacon/opencms-core#321]
When I'm uploading an image to a downloadgallery, the image isn't shown in the results-section of the gallery dialog by default.
I have to check the "Image Type" in the "Types"-Filter section first.
I think this is not the behaviour a content-editor expects. The results-section should show all files in that gallery by default.
It seems that this only happens, when the dialog refreshes after an upload.

This belongs to OpenCms 9.5.0. and 9.5.1 and maybe older versions also

**Comment by tHerrmann** [comment]
To avoid this issue you need to edit the configuration file /WEB-INF/config/opencms-vfs.xml.
Look for the node <type class="org.opencms.file.types.CmsResourceTypeImage" name="image" id="3"> and change <param name="gallery.type.names">imagegallery</param> to <param name="gallery.type.names">imagegallery|downloadgallery</param>

This will be fixed in the upcoming release of version 9.5.3.

**Comment by tHerrmann** [comment]
Fixed in branch_9_5_x will be released in version 9.5.3.
