### ISSUE TITLE
Wrong detail page url generation with multiple sites.

### ISSUE THREAD

**Issue by shaertling** [alkacon/opencms-core#368]
The same detail page url in different sites results in different urls.

Environment:
- OpenCms 9.5.2
- ROOT installation
- avoid of /opencms/opencms/

Scenario:
**Site1:**
www.site1.de
Detail-Page: /blog/index.html
urlName-Mapping: blog.html

www.site1.de/.content/.config
www.site1.de/.content/blog/blog-00001.xml
www.site1.de/blog/index.html

**Site2:**
www.site2.de
Detail-Page: /blog/index.html
urlName-Mapping: blog.html

www.site2.de/.content/.config
www.site2.de/.content/blog/blog-00001.xml
www.site2.de/blog/index.html

This scenario generates **www.site1.de/blog/blog.html** and **www.site2.de/blog.blog.html-00001**.
It should be **www.site2.de/blog/blog.html**.

The configuration .conf in the .content folder has no effect.

It seems that the urlName-Mapping isn't site unique but rather CMS wide without context.

**Comment by aKandzior** [comment]
The last sentence in the problem description actually is correct:
The urlName-Mapping must be unique without site context. 

That is the expected behavior. It was implemented this way so that a detail page name can be resolved with minimal database access. Otherwise resolving detail page names may lead to performance problems.

A workaround would be to ensure that different name mappings are used for every site, e.g. blog1.html, blog2.html etc.
