### ISSUE TITLE
OpenCMS JSP template

### ISSUE THREAD

**Issue by junaidbinsarfraz** [alkacon/opencms-core#385]
I am using opencms 10. 

Well have created simple jsp template by following [this][1] link

    <%@page buffer="none" session="false" trimDirectiveWhitespaces="true" %>
    <%@ taglib prefix="cms" uri="http://www.opencms.org/taglib/cms" %>
    <%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
    <%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
    <%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
    <!DOCTYPE html>
    <html>
    	<head>
    
    		<cms:enable-ade />
    
    	</head>
    	<body>
    
    		<div id="header">
    			<cms:container name="headercontainer" type="header" maxElements="1" />    	
    		</div>
    
    		<div id="window">
    			<cms:container name="centrecontainer" type="center" maxElements="8" detailview="true"/>
    		</div>
    
    		<div id="footerColumn">
    			<cms:container name="footercontainer" type="footer" maxElements="1"/>
    		</div>
    	</body>
    </html>

say it is `main.jsp`. After this I created a new `container-page` say `my-fist-template.html` and set following property 

    template = /system/modules/my.first.module/templates/main.jsp

Then I created a new *resource type* say *myResourceType*. I also created xsd and formatter for newly created resource type. 

After this I opened `my-fist-template.html` for editing. I was **unable** to add layout, simple slider, flexible content etc (every/default resource types created by opencms) **BUT** I was able to put my newly created resource type *`myResourceType`*. 

What am I missing?

  [1]: http://documentation.opencms.org/opencms-documentation/creating-a-website/creating-a-template-jsp/

**Comment by aKandzior** [comment]
I assume your template container configuration is not correct, but this is not a support forum (use the mailing list for that, which you already have done). 

You are apparently working with the OpenCms Apollo Template. 

My guess is that that your container type="center" is not configured for the formatters. It will not if you have not changed the formatter configurations of the Apollo modules. To verify, change the type of the container "center" to "element" and see if you can drop the "Content section" there now. 

The rest of the discussion should be on the mailing list. Closing this issue here.
