### ISSUE TITLE
UX: Enable keyboard editing in "Sitemap editor > Copy / target folder" and make filename configurable [Enhancement]

### ISSUE THREAD

**Issue by gallardo** [alkacon/opencms-core#437]
Clicking through the filetree is very cumbersome. It'd be very convenient to upgrade the `target folder` input field to a keyboard-editable one:

![screenshot_2016-10-11_14-42-42](https://cloud.githubusercontent.com/assets/790448/19270714/ab66f528-8fc1-11e6-8219-b687a50eb0ac.png)

As a natural follow-up enhancment, the target file name should also be configurable.

**Comment by aKandzior** [comment]
This is included in OpenCms 10.5!

**Comment by gallardo** [comment]
:confused: Looks like if https://github.com/alkacon/opencms-core/issues/438 had been implemented instead of this?

**Comment by aKandzior** [comment]
You are right it's #438 that has been implemented. 

We will add editing of the target path in the sitemap ASAP.

**Comment by aKandzior** [comment]
This will be included in the upcoming 10.5.1 release.

**Comment by gallardo** [comment]
Take this one with a grain of salt because I don't yet trust my build 100%. (In fact, I'm not reopening it until I can rebuild and retest, but perhaps someone jump-in and spares me some time.)

I'm experiencing some strange behaviour here.

First of all, on activating the menu, I get a dialogue with a disabled 'Ok' button:
![screenshot_2017-02-16_20-45-28](https://cloud.githubusercontent.com/assets/790448/23038094/0989c492-f489-11e6-9f1c-db883176a724.png).

When I edit the target field and select a new name (e.g. `/apollo-demo/home6/`, I get an 

> Error reading resource from path "/apollo-demo/home6/".

no matter what copy mode I choose. Notice that I have tested as Target folder:
- `/apollo-demo/home6`
- `/apollo-demo/home6/`
- `/apollo-demo/home/home6`

For what is worth, this is the (truncated) stacktrace:
```
org.opencms.file.CmsVfsResourceNotFoundException: Error reading resource from path "/apollo-demo/home6/".
	at org.opencms.file.CmsVfsResourceNotFoundException.createException(CmsVfsResourceNotFoundException.java:71)
	at org.opencms.db.CmsDbContext.throwException(CmsDbContext.java:335)
	at org.opencms.db.CmsDbContext.report(CmsDbContext.java:287)
	at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:5051)
	at org.opencms.file.CmsObject.readResource(CmsObject.java:3199)
	at org.opencms.ui.sitemap.CmsCopyPageDialog.onClickOk(CmsCopyPageDialog.java:143)
	at org.opencms.ui.sitemap.CmsCopyPageDialog$2.buttonClick(CmsCopyPageDialog.java:114)
	at sun.reflect.GeneratedMethodAccessor176.invoke(Unknown Source)
	...
Caused by: org.opencms.file.CmsVfsResourceNotFoundException: Unable to read resource "/apollo-demo/home6".
	at org.opencms.db.generic.CmsVfsDriver.readResource(CmsVfsDriver.java:2382)
	at org.opencms.db.CmsDriverManager.readResource(CmsDriverManager.java:7683)
	at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:7449)
	at org.opencms.db.CmsSecurityManager.readResource(CmsSecurityManager.java:5049)
	... 51 more
```

I can notice a few inconsistencies with the equivalent implementation for the 'Copy' dialog in the Explorer (https://github.com/alkacon/opencms-core/issues/438):
![screenshot_2017-02-16_20-53-56](https://cloud.githubusercontent.com/assets/790448/23038376/17bad17c-f48a-11e6-987c-1e5cae429dfb.png)

1. Different name for the target input field (`Target` vs `Target folder`)
2. Default target value: current directory vs source container page
3. The copy modes are named differently (`Copy container page and copy elements | Copy container page and reuse elements | Copy files, keep siblings | Copy files, also copy siblings | Copy folders, create siblings for all files` vs `Automatic | Copy elements | Reuse elements`)
4. The already mentioned 'Ok' button state
5. The explorer copy dialogue works on pressing 'Ok' by selecting a file name with a suffix (e.g. `home-copy` for the `home` copy). The sitemap copy dialogue apparently forces me to choose a name (if not, the Ok button remains disabled)

**Comment by aKandzior** [comment]
We will look into the issues with the Exceptions mentioned above:

Regarding the mentioned "inconsistencies":

1. The name should be "Target" in both dialogs.
2. The use case "Sitemap" and "Explorer" are similar but different in detail, so not all items in the copy dialogs can (or should) be the same. Here the Sitemap has no concept of a "current directory", so the default is the source page. We could use another default for the sitemap, but this should make sense in the context of the sitemap. If you have a good idea what would make better sense then the target page please let us know. 
3. See answer 2. In the explorer the container page copy is a special case. The regular copy case in the behavior of OpenCms has the options "Copy files..." etc. The new options have been added "on top".
4. The "Ok" button state is disabled since the default target is the source page and copying the page onto itself is very likely not what the user wants. So the user is forced to first change the target location. In the explorer it's perfectly fine that the resource is "duplicated" in the same folder so the ok button is enabled. If we have an idea for a "better" default in the sitemap (see 2.) then the "ok" button could be enabled here as well.
5. See 4. We thought that the "suffix" rule would not make that much sense in the sitemap. Keep in mind we actually deal with folder names here. Who wants a folder named "/home-0001/"?

**Comment by gallardo** [comment]
Thank you for your detailed answer.

I'd personally favour setting the "current directory" to the directory owning the selected container page, so that both dialogues could be almost identical.

But feel free to close this issue when the Error is fixed. Further enhancements could be tracked separately.

**Comment by gWestenberger** [comment]
I implemented several improvements on branch_10_5_x.

**Comment by danham567** [comment]
(Copy container page and copy elements | Copy container page and reuse elements | Copy files, keep siblings | Copy files, also copy siblings | Copy folders, create siblings for all files vs Automatic | Copy elements | Reuse elements)[121.pdf](https://github.com/alkacon/opencms-core/files/3290596/121.pdf)
