### ISSUE TITLE
<cms:navigation> does not check index.html in folder

### ISSUE THREAD

**Issue by kartobi** [alkacon/opencms-core#520]
We are using
```
<cms:navigation type="forFolder" var="myNav"/>
```
to build a subnavigation.

The tag uses navigation structure to build the nav entries, but does not check if the index.html in a folder was published. That results in dead links in online project.

**Comment by dSeidel** [comment]
If I understand correctly, you publish the folder with the relevant navigation properties, but not the index.html in the folder. This seems to be a very rare case and might be more a usage issue. We will not change the mechanism here, since it would on the one hand complicate the mechanism and on the other hand it's not clear, if a folder itself should be able to be in an navigation even without index.html and trigger some special handling. So changes might have unwanted side effects as well.
