### ISSUE TITLE
SVN/GIT and generally versioning support for both editors and module developers

### ISSUE THREAD

**Issue by ssklavos-ed** [alkacon/opencms-core#616]
Possibly this is a nice to have: Would that be possible to have svn/git support for editors? This would mean that an editor who has access to a OpenCMS workplace could commit his own changes, and have any other versioning capabilities. I am not sure if this is currently possible with the use of remote access (complex setup for editors), since I think that even the VFS was put in SVN, a specific used would be able to see others changes and commit them as well. Correct me please if I am wrong, but the versioning is not adequately covered in documentation and this is something that for sure needs improvement, since it is a very important/usual part of development + editing daily workflows.

**Comment by veggie4ever** [comment]
Hi,
I know, this is probably not exactly what you are looking for, but you may have a look at the OpenCms Maven plugin. 
https://opencms-maven.comundus.com/
The main focus of this plugin is, to ease the development process of OpenCms projects. But with a good setup and Maven configuration you might use it to put the contents of  your production site under version control. If you are interested, you'll find more information on [the official website of the plugin](https://opencms-maven.comundus.com/).

**Comment by ssklavos-ed** [comment]
Yes, I have already checked the plugin, this is mainly for developers, template developers etc. My point is mainly focused on editors who should be able to change site content, commit merge etc,

**Comment by dSeidel** [comment]
Hi, I'll close this feature request for now. OpenCms has with the "History" for single resources a (thought very limited) feature of version control for editors. Adding features like merging would probably be very complex or even impossible to make it the simple that editors can use it.
For developers, or version-controlled demo contents, you can and should checkin your modules to a version control system and since OpenCms 11 frequent updates (moving from development/test to production) become easier, since modules can be updated, ie. typically only changed files are exchanged.
