### ISSUE TITLE
opencms 11 beta Resource types application does not properly create content type

### ISSUE THREAD

**Issue by ssklavos-ed** [alkacon/opencms-core#620]
We noticed that while using the new resource types application, the wizard fails to automatically  add the newly created resource in the explorer types element of the opencms-modules.xml.  As a result it is not listed as a resource type in both the resource types application and in ADE editor wizard. Is it a bug of the application? Or we have to manually add the respective explorer type?

**Comment by sHuewe** [comment]
The app is supposed to add the explorer types settings. 

Until now, there is a validation missing for the field "Message Bundle". And if you enter an invalid resource path or the path of a resource which is not a property resource bundle the app fails in the beta version. This will be fixed in the release.

Other problems are not known until now. 
Is the app working for you if you ensure that the field for the message bundle is filled correctly (= root-path to a property resource bundle)? 
If not, i would be happy to see the opencms.log.

**Comment by ssklavos-ed** [comment]
Ok. It seems reasonable. However, what its the message bundle? Could you please provide some examples of a proper values, since there is no respective documentation in 11-beta and the tooltip is not descriptive enough.. 
Also, is there any 11-beta documentation which is under writing in which we could have access to?

**Comment by sHuewe** [comment]
There is no documentation for the 11-beta. But basic concepts in OpenCms are the same like before. For example message bundles are described here: https://documentation.opencms.org/opencms-documentation/localization/message-bundles/

In the dialog for creating new resource types you have to provide a message bundle (normally the one of the module you will add a new resource type to). The app stores the display name and the description of the new resource type in this message bundle.

One workflow which should work:
* Create a new module with the module app. If you don't change any of the ComboBoxes on the bottom of the dialog, the Module app will create an i18 folder with a message bundle for the new module.
* Go to the resource type app and click on the button to create a new resource type.
* Choose the module you have created in the first step
* The dialog should suggest the message bundle of the module by default, you don't need to change anything.

**Comment by ssklavos-ed** [comment]
Ok thank you. The described worklfow worked. I suppose this issue should remain open until the missing validation bug is fixed in the official 11 release.
