### ISSUE TITLE
Publishing renamed folder wrongly publishes subresources as well

### ISSUE THREAD

**Issue by kartobi** [alkacon/opencms-core#632]
Whenever a published folder gots renamed and published, all resources in that folder get published recursively, even if "Publish resources in folder" is not checked.

To repoduce in OpenCms 11_beta:

1) Create folder, subfolder and index.html; just publish folder (subfolder and index.html still have state "new"):
![image](https://user-images.githubusercontent.com/2276952/53097606-c65dc780-3519-11e9-8ac8-623de24e7169.png)
2) Rename folder to folder-renamed and direct publish just this folder:
![image](https://user-images.githubusercontent.com/2276952/53097644-dd041e80-3519-11e9-93a8-16da06dae6fb.png)
3) Subfolder and its index.html is published afterwards as well:
![image](https://user-images.githubusercontent.com/2276952/53097677-f0af8500-3519-11e9-8a39-6c85bf2858d7.png)
![image](https://user-images.githubusercontent.com/2276952/53097738-163c8e80-351a-11e9-9368-5c0f9a980bcf.png)

**Comment by gWestenberger** [comment]
This is intentional. Renaming a folder means changing the paths for all resources underneath it, so if any of these resources already exist in the Online project (have been published previously), they need to be published so their paths get updated in the Online tables. In your case, this doesn't seem to make sense because all of the sub-resources are new, but currently the system does not make any distinction between resource states in this case.

**Comment by kartobi** [comment]
I don't think it is intentional as it works (subfolders don't get published) when publishing "folder" when it is new.
Just is buggy when "folder" was published before.

**Comment by kartobi** [comment]
Any help on this problem here?

**Comment by gWestenberger** [comment]
Improved in branch_11_0_x: New subresources of moved folders are not automatically published any more.
