### ISSUE TITLE
OpenCms RC cannot setup in MS SQL Server

### ISSUE THREAD

**Issue by superc** [alkacon/opencms-core#638]
SA account can login and create database in SQL Server Management Studio.

![1-1](https://user-images.githubusercontent.com/3608960/56710954-2a3f7f00-675b-11e9-996e-4438c4dd9ac3.png)
![1-2](https://user-images.githubusercontent.com/3608960/56710956-2ad81580-675b-11e9-990f-88c741261a5e.png)
![2-1](https://user-images.githubusercontent.com/3608960/56710957-2b70ac00-675b-11e9-8cb9-7b5a1bfd8a53.png)
![2-2](https://user-images.githubusercontent.com/3608960/56710958-2b70ac00-675b-11e9-9bc7-c86da73b662d.png)

**Comment by tHerrmann** [comment]
Hi, in the last screen where the error dialog is displayed, please click on the 'Details' button. This should show the stack trace to the occurring exception. Please paste that trace here.

**Comment by gWestenberger** [comment]
Hello,

The setup wizard does not work with SQL server "named instances" by default, only with the default instance, since the full connection string is constructed by appending the DB name to the string you enter in the 'Connection string' field. 
You can make it work by manually changing the  mssql.constr.params entry in WEB-INF/setupdata/databases/mssql/database.properties to

mssql.constr.params=;instancename=SQLEXPRESS2008R2

before you start Tomcat.

**Comment by gWestenberger** [comment]
Sorry, wrong parameter: 

mssql.constr.params=;instance=SQLEXPRESS2008R2

**Comment by superc** [comment]
It's already installed.
Thanks.
