### ISSUE TITLE
Build failed with [ERROR] Hint: Check that your module inherits 'com.google.gwt.core.Core'

### ISSUE THREAD

**Issue by signbug** [alkacon/opencms-core#758]
I tried to build on 64-bit Windows 7 and Windows 10 and both failed.
1、Install jdk1.8.0_361 and git,
2、Clone the project without any modifications
3、Go to the opencms-core directory，run  `gradlew bindist`

 I also tried jdk1.8.0_92 and jdk1.8.0_121, none can be built.
Can someone tell me what I did wrong?Thank you!

```
> Task :gwt_org.opencms.ade.OpenCms
======================================================
Building GWT resources for org.opencms.ade.OpenCms
======================================================
Compiling module org.opencms.ade.OpenCms
   [ERROR] Hint: Check that your module inherits 'com.google.gwt.core.Core' either directly or indirectly (most often by inheriting module 'com.google.gwt.user.User')

> Task :gwt_org.opencms.ade.OpenCms FAILED

FAILURE: Build failed with an exception.
```

![build failed](https://user-images.githubusercontent.com/128784952/227455048-6085117e-34b3-41f8-9d64-40d78b582793.png)

**Comment by signbug** [comment]
@gWestenberger Can you fix it?

**Comment by gWestenberger** [comment]
No, I can't fix it because I don't know how (or if it's even possible on the OpenCms side).

I suspect (but don't know for certain) that it's the following issue on the GWT side:

https://github.com/gwtproject/gwt/issues/9101

(Gradle uses a classpath JAR to set the classpath on Windows, and some classes used by the GWT compiler to load resources apparently only check the java.class.path property and not the Class-Path manifest entries of classpath JARs.)

**Comment by rrosci** [comment]
Hi, I'm also having this problem on the build, how was it solved?
